// constants.js

export const paragraphs = [
  "La vida es un regalo valioso, disfrutala",
  "El sol brilla, el dia es hermoso",
  "Aprende del pasado, vive el presente",
  "Sueña grande, trabaja duro, logra todo",
  "La felicidad esta en las pequeñas cosas",
  "Un buen libro, una mente abierta",
  "El tiempo vuela, aprovecha cada instante",
  "Siempre hay algo por lo que agradecer",
  "La amistad verdadera es un tesoro",
  "Sonrie, el mundo te devuelve la sonrisa",
  "Cree en ti, eres capaz de todo",
  "Respira hondo, relaja tu mente ahora",
  "El camino es largo, sigue adelante",
  "Cada dia es una nueva oportunidad",
  "Se amable, deja tu huella positiva",
  "Escucha tu corazon, el te guiara",
  "La paciencia es una gran virtud",
  "Disfruta el viaje, no solo el destino",
  "El conocimiento es poder, aprende mas",
  "Nunca te rindas, persiste siempre",
  "La musica alegra el alma, escucha mas",
  "Un gesto amable cambia el dia",
  "Se tu mismo, los demas ya existen",
  "La naturaleza nos da mucha paz",
  "Siembra amor, cosecha felicidad",
  "El futuro es hoy, actua con valor",
  "La familia es el pilar de la vida",
  "Busca la luz en la oscuridad",
  "Vive el momento, no te preocupes",
  "El exito es la suma de esfuerzos",
  "La honestidad es la mejor politica",
  "Ayuda a otros, haz la diferencia",
  "Explora el mundo, descubre algo nuevo",
  "Los desafios te hacen mas fuerte",
  "El amor todo lo puede y lo logra",
  "Cuida tu cuerpo, es tu templo",
  "Piensa positivo, atrae lo bueno",
  "La fe mueve montañas, confia siempre",
  "El silencio es a veces la respuesta",
  "Deja ir lo que no te hace bien",
  "Celebra tus logros, grandes y pequeños",
  "La empatia es clave para entender",
  "Un abrazo sincero sana el alma",
  "El perdon libera tu corazon",
  "Comienza hoy, no esperes mas",
  "La gratitud abre puertas bonitas",
  "Respeta a todos, sin excepcion",
  "La imaginacion no tiene limites",
  "Acepta los cambios, fluye con ellos",
  "Haz lo que amas, ama lo que haces",
];

export const validInputKeys =
  "ABCDEFGHIJKLMNÑOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz,. ";

export const ignoredkeys = [
  "Shift",
  "CapsLock",
  "Control",
  "Alt",
  "Meta",
  "Tab",
  "Enter",
  "Delete",
  "ArrowLeft",
  "ArrowRight",
  "ArrowUp",
  "ArrowDown",
];
